name: cep_finder
description: A app to search ZIP codes and save addresses.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

 
  assets:
    - assets/images/home_background.png
    - assets/images/search_image.png
    - assets/images/saved_icon.png
    - assets/images/fav_icon.png
    - assets/images/home_icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        


